objects/Answer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Answer__c/fields/Read_More__c.field-meta.xml
<CustomField>
    <fullName>Read_More__c</fullName>
    <label>Read More</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Answer__c/fields/Read_More_Time__c.field-meta.xml
<CustomField>
    <fullName>Read_More_Time__c</fullName>
    <label>Read More Time</label>
    <precision>8</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

objects/Answer__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <precision>8</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

objects/Contact/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wyzsze</fullName>
            </value>
            <value>
                <fullName>Zawodowe</fullName>
            </value>
            <value>
                <fullName>Srednie</fullName>
            </value>
            <value>
                <fullName>Podstawowe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kobieta</fullName>
            </value>
            <value>
                <fullName>Mezczyzna</fullName>
            </value>
            <value>
                <fullName>Inna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contact/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <label>Additional Information</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question text</description>
    <label>Question</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Question__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interaktywna plansza</fullName>
            </value>
            <value>
                <fullName>Wiedza</fullName>
            </value>
            <value>
                <fullName>Preferencje</fullName>
            </value>
            <value>
                <fullName>Dane</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SurveyController.cls
public without sharing class SurveyController {
    @AuraEnabled(Cacheable=true)
    public static List<Question__c> getQuestions() {
        List<Question__c> questions = [
                SELECT Id,
                        Name,
                        Active__c,
                        Additional_Information__c,
                        Type__c,
                        Question__c,
                        Step__c,
                        Survey__c
                FROM Question__c
                ORDER BY Step__c
        ];
        return questions;
    }

    @AuraEnabled
    public static List<Answer__c> createSurveyAnswers(SurveyAnswersWrapper surveyAns) {
        Account acc = new Account();
        List<Account> accs = [SELECT Id FROM Account WHERE Name = 'Ankieta' LIMIT 1];
        if (accs.isEmpty()) {
            acc = new Account(Name = 'Ankieta');
            insert acc;
        } else {
            acc = accs.get(0);
        }

        List<AnswerWrapper> answers = (List<AnswerWrapper>) JSON.deserialize(surveyAns.answersAsJson, List<AnswerWrapper>.class);
        List<Answer__c> ansToInsert = new List<Answer__c>();

        Database.DMLOptions dml = new Database.DMLOptions();
        dml.duplicateRuleHeader.allowSave = true;
        Contact contact = new Contact();
        contact.LastName = 'User';
        contact.AccountId = acc.Id;
        contact.Email = 'user@user.com';
        Database.insert(contact, dml);

        for (AnswerWrapper ans : answers) {
            if (ans.questionName != 'Education' && ans.questionName != 'Gender' && ans.questionName != 'Age') {
                Answer__c answer = new Answer__c();
                answer.Answer__c = ans.value;
                answer.Question__c = ans.questionId;
                answer.Contact__c = contact.Id;
                answer.Time__c = ans.timeVal;
                answer.Read_More__c = ans.readMore;
                answer.Read_More_Time__c = ans.timeRM;
                answer.Name = String.valueOf(Datetime.now()) + ' - ' + ans.value;
                ansToInsert.add(answer);
            } else if (ans.questionName == 'Gender') {
                contact.Gender__c = ans.value;
            } else if (ans.questionName == 'Age') {
                contact.Age__c = Integer.valueof(ans.value);
            } else {
                contact.Education__c = ans.value;
            }
        }

        insert ansToInsert;
        update contact;
        return ansToInsert;
    }

    class SurveyAnswersWrapper {
        @AuraEnabled
        public String answersAsJson { get; set; }
    }

    class AnswerWrapper {
        public String value { get; set; }
        public String readMore { get; set; }
        public Integer timeVal { get; set; }
        public Integer timeRM { get; set; }
        public String questionId { get; set; }
        public String questionName { get; set; }
    }
}